### ISSUE TITLE
Introducing critical interaction

### ISSUE THREAD

**Issue by dunjaseselja** [daimpi/SocNetABM#2]
One way to represent critical interaction in Zollman's model is as follows:
given:
- T is a true theory and F is a false theory
- A's subjective probability of success of T and F are, respectively: Pa(T), Pa(F)
- for the sake if simplicity, I will speak of A's subjective probability after an update of information, as Pa*(T), Pa*(F) (where Pa(T), Pa(F) stand for the subjective assessments at the time point right before the given update);

if A is currently pursuing T, every time she receives information which is such that:
- Pa*(T) < Pa(T) or Pa*(F) > Pa(F), we say that she is involved in critical interaction;
if A is currently pursuing F, every time she receives information which is such that:
- Pa*(T) > Pa(T) or Pa*(F) < Pa(F), we say that she is involved in critical interaction.

Every time A is involved in critical interaction, at the next pull from T/F the objective probability of success (OPS) of the given theory will be:
if A is on T, her next pull will be from P*(T) = P(T) + 0,001
if A is on F, her next pull will be from P*(F) = P(F) - 0,001; (where P(T), P(F) are OPSs at the time point right before the update).

This also means that A should not jump immediately after being involved in critical interaction even if she usually would do so (i.e. even if Pa(her current theory) < Pa(the opposite theory)). That could maybe be managed via a jump-threshold, which we could keep to a minimum for now (maybe 10 will do?).

Please think critically about this proposal cause maybe there are some problems with it which I've overlooked :)

**Comment by daimpi** [comment]
Yes I think this is a good approach to capture the concept of critical interaction within this model.
Wrt jump-/strategy thresholds: I think we can vary them later on, as also without them there is - even in complete networks - the potential of scientists jumping forth and back between theories a few times before settling, which would suffice for critical interaction to have an effect.

For the modification of the OPSs: I'd suggest to go with a slightly more intricate formula: P*(x) = P(x) + f(d)
where x ∈ {T, F},
d = distance from P(x) to the actual probability of success (APS(F) = 0 and APS(T) = 1):
d = APS(x) - P(x)
and f(.) is a function with marginal returns proportional to d. 

An example for f would be: f(d) = d / 1000

This would represent a kind of "low hanging fruit" concept: When methodologies are not very advanced and therefore generate lot of misleading data (d is large), it is easy to improve the methodology, but the closer you get to the APS the harder it is to improve.

One more question we have to decide on: when do we check for critical interaction:

1.  once per tick - i.e. at the end of each full communication exchange 
2.  or once per information received - i.e. after each single incorporation of information from a scientist she shares with (this should probably not include her own pulls).

**Comment by dunjaseselja** [comment]
Sounds good to go with such a function! I like the motivation!
As for the question when critical interaction is checked for, i think 2 makes more sense.
Whether to include her own pulls or not is a good question. I'd say for the first version we don't do that, because we want to start from a simple scenario. In a future version we can include a feature where our scientists are cautious in various ways, one of which is being self-critical, and then we can include that too (if we at all decide to develop this feature further, that is).

**Comment by daimpi** [comment]
Ok, deal.

My concrete suggestion for the implementation would then be the following for the update of a scientists memory:

1. she integrates the information from her own pulls, which gives her a new posterior (not checking for critical interaction)
2. one after another she picks a random scientist she has a link with and integrates the information from the other scientists pulls which each time give her an updated posterior. So each time she checks if the critical interaction condition from above applies and if yes, updates her P(x) (the OPS for her current theory).
3. She checks which theory is the best according to her new posterior and if her current theory is not among the best theories she considers jumping to the other theory.

**Comment by dunjaseselja** [comment]
Sounds good!
In that case though, maybe we should take into account that all this critical interacting + new pulls will cost her time (since efficiency is a function of both time and success).
One way to add time here is to distinguish between "genuine" updates of information (your item 1) and updates triggered by critical interaction. A counter can run over only genuine updates of information, so that we run the model for a certain X number of such (genuine) updates. Agents who interact a lot will need more time-steps for them than those who interact less.
How does that sound?

**Comment by daimpi** [comment]
I'm not sure if I understood your last point:
We already have a "timer" for the genuine updates: The tick counter. Each scientist has exactly one "genuine update" per tick: the information from pulls from her respective slot machine. But why would scientists who interact more need more ticks?
Regarding the abort/exit criterion for our runs: I'd suggest instead of using something with an absolute value, we try to find an appropriate convergence criterion and measure the time needed wrt this criterion.

I'd suggest in order to keep the discussion structured we create a new issue for the discussion on time costs.

Edit: Issue #3 created

**Comment by dunjaseselja** [comment]
OK, as discussed, we should keep time calculation separately.
